# Generated by Django 5.0.6 on 2025-09-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='current_cycle_used_hours',
            field=models.DecimalField(decimal_places=2, help_text='The number of hours already used in the current 70-hour/8-day cycle.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_location',
            field=models.CharField(help_text='The starting point of the driver before the trip.', max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropoff_location',
            field=models.CharField(help_text='The drop-off location for the trip.', max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_location',
            field=models.CharField(help_text='The pickup location for the trip.', max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores the calculated route and ELD log data from the API call.', null=True),
        ),
    ]
